/* Shared "Copy / Share / Save as PDF" actions for AI replies.
   Exposes:
     window.actionButtonsHTML()  -> string of HTML for the toolbar
     window.wireActionButtons(scope) -> attaches handlers inside scope
*/
(function () {
  const TOOLBAR_HTML = `
    <div class="msg-actions" data-actions>
      <button type="button" class="msg-action" data-action="copy" title="Copy reply">
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
        <span>Copy</span>
      </button>
      <button type="button" class="msg-action" data-action="share" title="Share">
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></svg>
        <span>Share</span>
      </button>
      <button type="button" class="msg-action" data-action="pdf" title="Save as PDF">
        <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
        <span>Save PDF</span>
      </button>
    </div>`;

  function plainTextFromHTML(node) {
    const clone = node.cloneNode(true);
    clone.querySelectorAll("[data-actions]").forEach((el) => el.remove());
    return (clone.innerText || clone.textContent || "").trim();
  }

  function findReplyContainer(btn) {
    const wrap = btn.closest("[data-reply], .msg, .result-area");
    if (!wrap) return null;
    const doc = wrap.querySelector(".doc");
    return doc || wrap;
  }

  async function handleCopy(btn) {
    const container = findReplyContainer(btn);
    if (!container) return;
    const text = plainTextFromHTML(container);
    try {
      await navigator.clipboard.writeText(text);
      flash(btn, "Copied ✓");
    } catch {
      flash(btn, "Copy failed");
    }
  }

  async function handleShare(btn) {
    const container = findReplyContainer(btn);
    if (!container) return;
    const text = plainTextFromHTML(container);
    const url = window.location.href;
    if (navigator.share) {
      try {
        await navigator.share({
          title: document.title,
          text: text.slice(0, 800),
          url: url,
        });
      } catch { /* user cancelled */ }
    } else {
      try {
        await navigator.clipboard.writeText(`${text}\n\n— from ${url}`);
        flash(btn, "Copied for sharing ✓");
      } catch {
        flash(btn, "Share unavailable");
      }
    }
  }

  function handlePDF(btn) {
    const container = findReplyContainer(btn);
    if (!container) return;
    const html = container.innerHTML;
    const title = document.title || "AI Digital Health Assistant";
    const win = window.open("", "_blank");
    if (!win) { flash(btn, "Popup blocked"); return; }
    win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
      <style>
        body { font-family: Inter, Segoe UI, sans-serif; color: #0f172a; max-width: 800px; margin: 24px auto; padding: 0 16px; line-height: 1.55; }
        h1, h2, h3 { color: #0284c7; font-family: 'Space Grotesk', Inter, sans-serif; }
        table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 14px; }
        th, td { border: 1px solid #cbd5e1; padding: 6px 10px; text-align: left; }
        th { background: #e0f2fe; }
        code { background: #e0f2fe; padding: 1px 6px; border-radius: 4px; }
        .footer { margin-top: 28px; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 10px; }
      </style></head><body>
      <h1>${title}</h1>
      ${html}
      <div class="footer">Generated by AI Digital Health Assistant · Educational use only · Not a substitute for medical advice.</div>
      <script>window.onload = () => { window.print(); }<\/script>
      </body></html>`);
    win.document.close();
  }

  function flash(btn, msg) {
    const span = btn.querySelector("span");
    if (!span) return;
    const original = span.textContent;
    span.textContent = msg;
    btn.classList.add("is-flash");
    setTimeout(() => { span.textContent = original; btn.classList.remove("is-flash"); }, 1500);
  }

  window.actionButtonsHTML = function () { return TOOLBAR_HTML; };

  window.wireActionButtons = function (scope) {
    if (!scope) return;
    scope.querySelectorAll("[data-actions]").forEach((bar) => {
      if (bar.dataset.wired === "1") return;
      bar.dataset.wired = "1";
      bar.addEventListener("click", (e) => {
        const btn = e.target.closest(".msg-action");
        if (!btn) return;
        const action = btn.dataset.action;
        if (action === "copy") handleCopy(btn);
        else if (action === "share") handleShare(btn);
        else if (action === "pdf") handlePDF(btn);
      });
    });
  };
})();
